name: Assign PR to creator

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        uses: toshimaru/auto-author-assign@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
